// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: proto/gorono.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GMetr struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ID            string                 `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	MType         string                 `protobuf:"bytes,2,opt,name=MType,proto3" json:"MType,omitempty"`
	Delta         int64                  `protobuf:"varint,3,opt,name=Delta,proto3" json:"Delta,omitempty"`
	Value         float64                `protobuf:"fixed64,4,opt,name=Value,proto3" json:"Value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GMetr) Reset() {
	*x = GMetr{}
	mi := &file_proto_gorono_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GMetr) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GMetr) ProtoMessage() {}

func (x *GMetr) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gorono_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GMetr.ProtoReflect.Descriptor instead.
func (*GMetr) Descriptor() ([]byte, []int) {
	return file_proto_gorono_proto_rawDescGZIP(), []int{0}
}

func (x *GMetr) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *GMetr) GetMType() string {
	if x != nil {
		return x.MType
	}
	return ""
}

func (x *GMetr) GetDelta() int64 {
	if x != nil {
		return x.Delta
	}
	return 0
}

func (x *GMetr) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

type MBunch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bunch         []*GMetr               `protobuf:"bytes,1,rep,name=bunch,proto3" json:"bunch,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MBunch) Reset() {
	*x = MBunch{}
	mi := &file_proto_gorono_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MBunch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MBunch) ProtoMessage() {}

func (x *MBunch) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gorono_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MBunch.ProtoReflect.Descriptor instead.
func (*MBunch) Descriptor() ([]byte, []int) {
	return file_proto_gorono_proto_rawDescGZIP(), []int{1}
}

func (x *MBunch) GetBunch() []*GMetr {
	if x != nil {
		return x.Bunch
	}
	return nil
}

type BunchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         string                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"` // ошибка
	OutData       string                 `protobuf:"bytes,2,opt,name=outData,proto3" json:"outData,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BunchResponse) Reset() {
	*x = BunchResponse{}
	mi := &file_proto_gorono_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BunchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BunchResponse) ProtoMessage() {}

func (x *BunchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gorono_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BunchResponse.ProtoReflect.Descriptor instead.
func (*BunchResponse) Descriptor() ([]byte, []int) {
	return file_proto_gorono_proto_rawDescGZIP(), []int{2}
}

func (x *BunchResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *BunchResponse) GetOutData() string {
	if x != nil {
		return x.OutData
	}
	return ""
}

var File_proto_gorono_proto protoreflect.FileDescriptor

const file_proto_gorono_proto_rawDesc = "" +
	"\n" +
	"\x12proto/gorono.proto\x12\x06gorono\"Y\n" +
	"\x05GMetr\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\tR\x02ID\x12\x14\n" +
	"\x05MType\x18\x02 \x01(\tR\x05MType\x12\x14\n" +
	"\x05Delta\x18\x03 \x01(\x03R\x05Delta\x12\x14\n" +
	"\x05Value\x18\x04 \x01(\x01R\x05Value\"-\n" +
	"\x06MBunch\x12#\n" +
	"\x05bunch\x18\x01 \x03(\v2\r.gorono.GMetrR\x05bunch\"?\n" +
	"\rBunchResponse\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05error\x12\x18\n" +
	"\aoutData\x18\x02 \x01(\tR\aoutData2;\n" +
	"\x06Metric\x121\n" +
	"\bAddBunch\x12\x0e.gorono.MBunch\x1a\x15.gorono.BunchResponseB\x0eZ\fgorono/protob\x06proto3"

var (
	file_proto_gorono_proto_rawDescOnce sync.Once
	file_proto_gorono_proto_rawDescData []byte
)

func file_proto_gorono_proto_rawDescGZIP() []byte {
	file_proto_gorono_proto_rawDescOnce.Do(func() {
		file_proto_gorono_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_gorono_proto_rawDesc), len(file_proto_gorono_proto_rawDesc)))
	})
	return file_proto_gorono_proto_rawDescData
}

var file_proto_gorono_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_gorono_proto_goTypes = []any{
	(*GMetr)(nil),         // 0: gorono.GMetr
	(*MBunch)(nil),        // 1: gorono.MBunch
	(*BunchResponse)(nil), // 2: gorono.BunchResponse
}
var file_proto_gorono_proto_depIdxs = []int32{
	0, // 0: gorono.MBunch.bunch:type_name -> gorono.GMetr
	1, // 1: gorono.Metric.AddBunch:input_type -> gorono.MBunch
	2, // 2: gorono.Metric.AddBunch:output_type -> gorono.BunchResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_gorono_proto_init() }
func file_proto_gorono_proto_init() {
	if File_proto_gorono_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_gorono_proto_rawDesc), len(file_proto_gorono_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_gorono_proto_goTypes,
		DependencyIndexes: file_proto_gorono_proto_depIdxs,
		MessageInfos:      file_proto_gorono_proto_msgTypes,
	}.Build()
	File_proto_gorono_proto = out.File
	file_proto_gorono_proto_goTypes = nil
	file_proto_gorono_proto_depIdxs = nil
}
